"""Generate notebooks/02_trip_toughening.ipynb from this script.

Re-generate with:
    uv run python scripts/build_trip_notebook.py
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf


def md(*lines: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell("\n".join(lines))


def code(*lines: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell("\n".join(lines))


CELLS: list[nbf.NotebookNode] = [
    md(
        "# TRIP Toughening Submodel — Patel-Cohen + Olson-Cohen",
        "",
        "Phase 3 walkthrough. Reverted austenite films at lath boundaries can",
        "transform to martensite under stress (Patel-Cohen) or strain (Olson-Cohen)",
        "at the crack tip — the volume-expanding γ→α′ transformation provides crack-tip",
        "shielding. This notebook:",
        "",
        "1. Reproduces Patel-Cohen 1953 Table I dM_s/dσ slopes for Fe-Ni alloys.",
        "2. Reproduces Olson-Cohen 1975 / Angel 1954 304 SS f_α′(ε) curves.",
        "3. Sets up the M54 calibration from your cw/cr austenite measurements.",
        "",
        "See [`index/trip-foundations-index.md`](../index/trip-foundations-index.md) for",
        "the full equation derivation.",
    ),
    md("## 0. Setup"),
    code(
        "import math",
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "",
        "from m54model.toughening import (",
        "    OlsonCohenParams, olson_cohen_volume_fraction, fit_olson_cohen,",
        "    patel_cohen_max_work, patel_cohen_ms_shift, patel_cohen_optimal_orientation,",
        ")",
        "",
        "%matplotlib inline",
        "plt.rcParams['figure.dpi'] = 110",
    ),
    md(
        "## 1. Patel-Cohen 1953 — stress-assisted γ → α′ M_s shift",
        "",
        "For Fe-Ni alloys with γ₀ = 0.20 (transformation shear) and ε₀ = 0.04 (dilatation),",
        "the optimal habit-plane orientation maximizing U = τγ₀ + σε₀ is at 2θ ≈ 79°.",
    ),
    code(
        "GAMMA0, EPS0 = 0.20, 0.04",
        "DF_DT_FE_NI_C = 1.33  # cal/(mol·K) for 0.5C-20Ni-bal-Fe",
        "DF_DT_FE_NI = 1.23   # cal/(mol·K) for 70Fe-30Ni",
        "VM = 7.1e-6           # m³/mol austenite molar volume",
        "ONE_KSI_MPA = 6.895",
        "",
        "theta_opt = patel_cohen_optimal_orientation(GAMMA0, EPS0)",
        "print(f'Optimal habit-plane angle: 2θ = {math.degrees(2*theta_opt):.2f}° (PC: 78.7°)')",
        "print()",
        "print('dM_s/dσ for Fe-Ni-C alloys (PC 1953 Table I anchors):')",
        "for mode, dF_dT, expected in [",
        "    ('tension',     DF_DT_FE_NI_C,  '+1.07'),",
        "    ('compression', DF_DT_FE_NI_C,  '+0.72'),",
        "    ('hydrostatic', DF_DT_FE_NI,    '-0.38'),",
        "]:",
        "    dMs = patel_cohen_ms_shift(ONE_KSI_MPA, GAMMA0, EPS0, dF_dT, VM, mode=mode)",
        "    print(f'  {mode:13s}: model {dMs:+5.2f} °C/ksi   PC says {expected} °C/ksi')",
    ),
    md(
        "### M_s shift vs applied stress — visualize across all three loading modes",
        "",
        "Patel-Cohen 1953 Fig. 1 reproduction. Tension > compression because both",
        "shear and normal components aid transformation under tension; in compression",
        "the normal component opposes the +4 % volume expansion of γ→α′.",
    ),
    code(
        "sigma_ksi = np.linspace(0, 30, 30)",
        "sigma_MPa = sigma_ksi * ONE_KSI_MPA",
        "",
        "fig, ax = plt.subplots(figsize=(8, 5))",
        "for mode, dF_dT, color in [",
        "    ('tension',     DF_DT_FE_NI_C,  '#1f78b4'),",
        "    ('compression', DF_DT_FE_NI_C,  '#33a02c'),",
        "    ('hydrostatic', DF_DT_FE_NI,    '#e31a1c'),",
        "]:",
        "    dMs = [patel_cohen_ms_shift(s, GAMMA0, EPS0, dF_dT, VM, mode=mode) for s in sigma_MPa]",
        "    ax.plot(sigma_ksi, dMs, '-', color=color, label=mode)",
        "ax.axhline(0, color='black', linewidth=0.5)",
        "ax.set_xlabel('Applied stress (ksi)')",
        "ax.set_ylabel('ΔM_s (°C)')",
        "ax.set_title('Patel-Cohen 1953 Fig. 1 reproduction — Fe-Ni-C')",
        "ax.legend()",
        "ax.grid(alpha=0.4)",
        "fig.tight_layout()",
        "plt.show()",
    ),
    md(
        "## 2. Olson-Cohen 1975 — strain-induced kinetics",
        "",
        "Master equation:  f_α′(ε) = 1 − exp{−β · [1 − exp(−α · ε)]ⁿ}",
        "",
        "where α captures shear-band-formation rate (depends on stacking-fault energy)",
        "and β captures the probability that a shear-band intersection nucleates an",
        "α′ embryo (sigmoidal in T, saturates near 2.0 at low T, decays to 0 above M_d).",
    ),
    code(
        "# Angel 1954 304 SS, Olson-Cohen Fig. 2(a, b) parameters at five temperatures.",
        "ANGEL_PARAMS = {",
        "    -188: OlsonCohenParams(alpha=12.9,  beta=2.00, n=4.5, T_celsius=-188),",
        "     -70: OlsonCohenParams(alpha=7.0,   beta=2.00, n=4.5, T_celsius=-70),",
        "     -30: OlsonCohenParams(alpha=5.0,   beta=1.70, n=4.5, T_celsius=-30),",
        "       0: OlsonCohenParams(alpha=4.0,   beta=1.00, n=4.5, T_celsius=0),",
        "      22: OlsonCohenParams(alpha=3.55,  beta=0.30, n=4.5, T_celsius=22),",
        "}",
        "",
        "eps = np.linspace(0, 0.85, 60)",
        "fig, ax = plt.subplots(figsize=(8, 5))",
        "cmap = plt.get_cmap('coolwarm_r')",
        "Ts = sorted(ANGEL_PARAMS, reverse=True)",
        "for i, T in enumerate(Ts):",
        "    p = ANGEL_PARAMS[T]",
        "    fa = [olson_cohen_volume_fraction(e, p) for e in eps]",
        "    ax.plot(eps, fa, '-', color=cmap(i / max(1, len(Ts)-1)), label=f'T = {T} °C')",
        "ax.set_xlabel('Plastic strain ε')",
        "ax.set_ylabel('Strain-induced α′ vol fraction f_α′')",
        "ax.set_title('Olson-Cohen 1975 Fig. 1 reproduction — Angel 1954 304 SS')",
        "ax.legend(loc='lower right')",
        "ax.grid(alpha=0.4)",
        "ax.set_xlim(0, 0.85)",
        "ax.set_ylim(0, 1.0)",
        "fig.tight_layout()",
        "plt.show()",
    ),
    md(
        "### Fitter sanity check",
        "",
        "Generate synthetic data from a known α, β; verify the fitter recovers them.",
    ),
    code(
        "true_p = OlsonCohenParams(alpha=12.9, beta=2.0, n=4.5, T_celsius=-188)",
        "eps_obs = np.linspace(0.05, 0.6, 12)",
        "f_obs = [olson_cohen_volume_fraction(e, true_p) for e in eps_obs]",
        "fit = fit_olson_cohen(list(eps_obs), f_obs, n=4.5, T_celsius=-188)",
        "print(f'True:  α={true_p.alpha:.3f}, β={true_p.beta:.3f}')",
        "print(f'Fit:   α={fit.alpha:.3f}, β={fit.beta:.3f}')",
        "print(f'Error: Δα/α = {abs(fit.alpha-true_p.alpha)/true_p.alpha*100:.2f} %, "
        "Δβ/β = {abs(fit.beta-true_p.beta)/true_p.beta*100:.2f} %')",
    ),
    md(
        "## 3. M54 cw/cr austenite data — and the non-monotonic finding",
        "",
        "ASTAR precession-diffraction-mapped FCC γ phase fractions at 0/20/40/60 %",
        "cumulative cold rolling, both at the rolling **surface** and through-thickness",
        "**core** (median along ND-midplane). Surface error bars are 1σ from multiple",
        "ASTAR maps.",
        "",
        "**Surprise:** austenite content is *non-monotonic* in CR. It drops from",
        "0 → 20 % CR (classical TRIP — austenite converts to α′), then **rises sharply**",
        "at 40 % CR (the surface jumps from 0.5 % to 26.4 %!), and partially retransforms",
        "at 60 %. This is *not* what Olson-Cohen describes. See FINDINGS.md §5 for the",
        "full discussion of candidate mechanisms (adiabatic-heating-driven reverse",
        "transformation, mechanical austenite formation in shear-band cellular networks,",
        "TWIP-like substructure stabilization).",
    ),
    code(
        "from m54model.calibration.user_trip_data import (",
        "    USER_M54_CW_AUSTENITE_SURFACE,",
        "    USER_M54_CW_AUSTENITE_CORE,",
        "    cw_pct_to_true_strain,",
        ")",
        "",
        "for label, data in [('surface', USER_M54_CW_AUSTENITE_SURFACE),",
        "                     ('core',    USER_M54_CW_AUSTENITE_CORE)]:",
        "    print(f'=== {label} ===')",
        "    for p in data:",
        "        std = f' ± {p.f_austenite_std:.3f}' if p.f_austenite_std else ''",
        "        eps_eq = cw_pct_to_true_strain(p.cw_pct) if p.cw_pct > 0 else 0.0",
        "        print(f'  CR={p.cw_pct:4.0f}%  ε={eps_eq:.3f}  f_A = {p.f_austenite:.3f}{std}')",
        "    print()",
    ),
    md(
        "### Plot the data — the spike at 40 % CR is the central finding",
    ),
    code(
        "fig, ax = plt.subplots(figsize=(9, 5))",
        "for data, color, marker, label in [",
        "    (USER_M54_CW_AUSTENITE_SURFACE, '#e31a1c', 'o', 'surface'),",
        "    (USER_M54_CW_AUSTENITE_CORE,    '#1f78b4', 's', 'core (median)'),",
        "]:",
        "    cws = [p.cw_pct for p in data]",
        "    fas = [p.f_austenite * 100 for p in data]",
        "    err = [(p.f_austenite_std or 0) * 100 for p in data]",
        "    ax.errorbar(cws, fas, yerr=err, marker=marker, color=color, label=label, markersize=8, capsize=4)",
        "ax.axvspan(0, 22, color='green', alpha=0.10, label='classical TRIP regime (0→20%)')",
        "ax.axvspan(22, 60, color='orange', alpha=0.10, label='non-monotonic regime (>20%)')",
        "ax.set_xlabel('Cumulative cold-rolling reduction (%)')",
        "ax.set_ylabel('Austenite vol fraction f_A (%)')",
        "ax.set_title('M54 austenite content vs CR — non-monotonic')",
        "ax.legend()",
        "ax.grid(alpha=0.4)",
        "fig.tight_layout()",
        "plt.show()",
    ),
    md(
        "### Try the fit — and observe why it fails",
        "",
        "Calling `m54_olson_cohen_fit_from_user_data` with the default",
        "`fit_only_monotonic_prefix=True` raises because the monotonic prefix has only",
        "two points. If we *force* a fit on all 4 points, the optimizer rails α to its",
        "upper bound — a clear signal the model is wrong for this data.",
    ),
    code(
        "from m54model.calibration.user_trip_data import m54_olson_cohen_fit_from_user_data",
        "",
        "try:",
        "    m54_olson_cohen_fit_from_user_data(USER_M54_CW_AUSTENITE_SURFACE)",
        "except ValueError as e:",
        "    print(f'Default (safe) fit refused: {e}')",
        "print()",
        "",
        "fit_anyway = m54_olson_cohen_fit_from_user_data(",
        "    USER_M54_CW_AUSTENITE_SURFACE, fit_only_monotonic_prefix=False",
        ")",
        "print(f'Forced fit on all 4 points: α={fit_anyway.alpha:.2f}, β={fit_anyway.beta:.2f}')",
        "print('  → α railed to its upper bound; the fit is meaningless.')",
    ),
    md(
        "### Interpretation",
        "",
        "Until we model the austenite-formation/stabilization mechanism that kicks in",
        "above ~20 % CR, the path forward for crack-tip TRIP modeling is:",
        "",
        "- **Use Olson-Cohen with literature-analog (α, β)** — e.g., Cho 2015 H600 Co-Ni",
        "  values, or 304 SS at room temperature — explicitly noting this as a",
        "  Phase 3.5 calibration gap.",
        "- **Restrict any quantitative TRIP claim to the 0 → 20 % CR regime** for now.",
        "- **Scope a Phase 3.6 model** that combines forward γ→α′ (Olson-Cohen) with a",
        "  competing α′→γ reverse mechanism (likely thermally-driven from rolling-surface",
        "  adiabatic heating, or strain-localized via shear-band cellular substructure).",
        "  The 4:1 surface:core ratio at 40 % CR is the smoking gun for surface-localized",
        "  heating or shear partitioning.",
    ),
    md(
        "## 3b. Phase 3.6d — predict σ_y(CR) and compare to user tensile",
        "",
        "Now that we have user-measured GND density, ASTAR f_A, and tensile",
        "data at 0/47/53/60 % CR, we can build a per-CR state factory and",
        "compare model predictions to measurements.",
        "",
        "**Approach:** `m54_af_t516_10_cw(cw_pct, location)` returns a",
        "`MicrostructuralState` with the user's BCC GND density and surface- or",
        "core-localized f_A swapped in. Block width, M2C population, and matrix",
        "composition are held at the AF + T516/10 baseline (cold rolling at room",
        "temperature doesn't move them).",
        "",
        "Predicted σ_y is then strain-rate-corrected by ×1.054 (200× rate ratio,",
        "m=0.01) for direct comparison to the user's tensile data measured at",
        "10⁻¹ s⁻¹.",
    ),
    code(
        "from m54model.calibration import predict_cw_cr_sweep, tensile_for_cr",
        "import pandas as pd",
        "",
        "# Default 'core' location is the right comparison for bulk tensile bars",
        "# (surface f_A spike at 40 % CR is not representative of the bulk).",
        "core_rows = predict_cw_cr_sweep(location='core')",
        "surf_rows = predict_cw_cr_sweep(location='surface')",
        "df = pd.DataFrame([",
        "    {",
        "        'CR%':         f\"{r['cw_pct']:.0f}\",",
        "        'σ_y model (core)':    f\"{r['sigma_y_user_rate_MPa']:.0f}\",",
        "        'σ_y model (surface)': f\"{s['sigma_y_user_rate_MPa']:.0f}\",",
        "        'σ_y measured':        (f\"{r['sigma_y_meas_MPa']:.0f} ± {r['sigma_y_meas_std_MPa']:.0f}\" if r['sigma_y_meas_MPa'] else '---'),",
        "        'miss% (core)':        (f\"{r['miss_pct']:+.1f}%\" if r['miss_pct'] is not None else '---'),",
        "    }",
        "    for r, s in zip(core_rows, surf_rows)",
        "])",
        "df.set_index('CR%')",
    ),
    md(
        "### Predicted vs measured σ_y across the CR sweep",
        "",
        "Bars: model (core); error caps on measured σ_y. The CR-sweep tensile",
        "data at 47 % and 53 % is plotted separately because it doesn't have",
        "matching ASTAR/GND inputs (the cw/cr microstructure series stops at",
        "20/40/60 %).",
    ),
    code(
        "from m54model.calibration import USER_M54_TENSILE",
        "",
        "fig, ax = plt.subplots(figsize=(9, 5))",
        "cws = [r['cw_pct'] for r in core_rows]",
        "model_core = [r['sigma_y_user_rate_MPa'] for r in core_rows]",
        "model_surf = [r['sigma_y_user_rate_MPa'] for r in surf_rows]",
        "ax.plot(cws, model_core, 'o-', color='#1f78b4', linewidth=2, markersize=10, label='Model (core f_A)')",
        "ax.plot(cws, model_surf, 's--', color='#a6cee3', linewidth=1.5, markersize=8, label='Model (surface f_A)')",
        "",
        "# Measured tensile points (cw_pct from USER_M54_TENSILE).",
        "tens_cw = [p.cw_pct for p in USER_M54_TENSILE]",
        "tens_y = [p.sigma_y_MPa for p in USER_M54_TENSILE]",
        "tens_err = [p.sigma_y_std_MPa for p in USER_M54_TENSILE]",
        "ax.errorbar(tens_cw, tens_y, yerr=tens_err, fmt='D', color='#e31a1c',",
        "            markersize=10, capsize=5, label='Measured (1e-1 s⁻¹)')",
        "",
        "ax.set_xlabel('Cumulative cold-rolling reduction (%)')",
        "ax.set_ylabel('σ_y (MPa, at user strain rate)')",
        "ax.set_title('Phase 3.6d — model σ_y(CR) vs user tensile')",
        "ax.legend(loc='lower right')",
        "ax.grid(alpha=0.4)",
        "ax.set_ylim(1100, 2100)",
        "fig.tight_layout()",
        "plt.show()",
    ),
    md(
        "**Reading the gap:**",
        "",
        "- **0 % CR**: model **over-predicts** by ~10 % (1420 vs 1300 MPa).",
        "  Likely the cross-rolled prior history (multi-axial deformation",
        "  before the temper) producing a coarser equivalent block than Sun's",
        "  simple-AF assumption.",
        "- **20-40 % CR**: model jumps with the GND density rise (1.6 → 6.3 →",
        "  7.9 × 10¹⁵ m⁻²). Surface-curve dips at 40 % CR because the f_A spike",
        "  (26.4 % surface) drags down the rule-of-mixtures correction. Core",
        "  curve stays high because core f_A is more modest (9.9 %). Bulk XRD V_γ",
        "  at 40 % is essentially zero — the surface phenomenon doesn't",
        "  represent the bulk material the tensile bar samples (see FINDINGS",
        "  §6 Phase 3.6b).",
        "- **60 % CR**: model **under-predicts** by ~16 % (1589 vs 1900 MPa).",
        "  Most plausible missing contributions: (a) statistically-stored",
        "  dislocations on top of GND (could double σ_ρ in heavy CW), (b)",
        "  sub-block refinement creating a Hall-Petch term not captured by",
        "  block-based σ_HP (the user's ASTAR shows 51-57 nm 'grains' at 60 %",
        "  core — way below the 0.48 µm block scale), (c) deformation-induced",
        "  micro-precipitation consuming residual C (Phase 3.6b α₀ contraction",
        "  evidence).",
        "",
        "Adding any of these would require new model physics — Phase 3.6e+",
        "scope. For now the gap is documented and the direction-of-effect",
        "(model σ_y rises with CR but not as fast as measured) is at least",
        "qualitatively right.",
    ),
    md(
        "### Phase 3.6e — adding an SSD multiplier on top of GND",
        "",
        "ASTAR-PED measures only **geometrically necessary dislocations**",
        "(GND); statistically-stored dislocations (SSDs) are absent. Lit-",
        "review (Galindo-Nava 2015, Wang 2024, Borbely 2022, Krauss 1999)",
        "found NO paper in our refs that explicitly partitions ρ_GND from",
        "ρ_SSD in the strengthening law — most use XRD-Williamson-Hall total",
        "ρ. So we expose `ssd_multiplier` (default 1.0 = GND only) and sweep",
        "to see what value would close the 60 % CR gap.",
    ),
    code(
        "ks = (1.0, 1.5, 2.0, 2.5, 3.0)",
        "rows = []",
        "for k in ks:",
        "    sweep = predict_cw_cr_sweep(location='core', ssd_multiplier=k)",
        "    for r in sweep:",
        "        rows.append({'CR%': r['cw_pct'], 'k': k,",
        "                     'σ_y': r['sigma_y_user_rate_MPa'],",
        "                     'meas': r['sigma_y_meas_MPa'],",
        "                     'miss%': r['miss_pct']})",
        "df = pd.DataFrame(rows)",
        "pivot = df.pivot(index='CR%', columns='k', values='σ_y')",
        "pivot['measured'] = [tensile_for_cr(c).sigma_y_MPa if c in (0, 60) else None for c in pivot.index]",
        "pivot",
    ),
    code(
        "fig, ax = plt.subplots(figsize=(9, 5))",
        "for k, color in zip(ks, plt.get_cmap('viridis')(np.linspace(0.1, 0.85, len(ks)))):",
        "    rows = predict_cw_cr_sweep(location='core', ssd_multiplier=k)",
        "    cws = [r['cw_pct'] for r in rows]",
        "    ys = [r['sigma_y_user_rate_MPa'] for r in rows]",
        "    ax.plot(cws, ys, 'o-', color=color, markersize=8, label=f'k = {k:.1f}')",
        "tens_cw = [p.cw_pct for p in USER_M54_TENSILE]",
        "tens_y = [p.sigma_y_MPa for p in USER_M54_TENSILE]",
        "tens_err = [p.sigma_y_std_MPa for p in USER_M54_TENSILE]",
        "ax.errorbar(tens_cw, tens_y, yerr=tens_err, fmt='D', color='red',",
        "            markersize=10, capsize=5, label='Measured')",
        "ax.set_xlabel('CR (%)')",
        "ax.set_ylabel('σ_y (MPa, user rate)')",
        "ax.set_title('SSD-multiplier sensitivity — k=2.5 closes the 60 % gap but blows up 0 %')",
        "ax.legend(loc='lower right')",
        "ax.grid(alpha=0.4)",
        "fig.tight_layout()",
        "plt.show()",
    ),
    md(
        "**Reading the sensitivity:** k=1.0 (default) under-predicts at 60 %",
        "(−16 %); k=2.5 closes the gap to <1 %; but the same k=2.5 makes 0 %",
        "CR over-predict by +23 % (vs the original +9 %). One uniform multiplier",
        "can't fix both ends — the 0 % CR over-prediction is a SEPARATE issue",
        "(coarser equivalent block from cross-rolled prior history), not a",
        "missing SSD term. The right calibration anchor would be a modified",
        "Williamson-Hall analysis on the user's existing XRD spectra at all",
        "four CR conditions, which would give us ρ_total directly per-sample.",
        "Phase 3.6e+ deliverable.",
    ),
    md(
        "## 4. Where this goes next — Phase 3.5",
        "",
        "With (α, β) calibrated for M54 reverted austenite, the next deliverable is",
        "a **crack-tip TRIP K_IC contribution**:",
        "",
        "1. At the crack tip, compute the local stress + strain field (HRR or",
        "   calibrated effective-stress proxy).",
        "2. For each material point in the plastic zone:",
        "   - Apply Patel-Cohen `U = τγ₀ + σε₀` to find stress-assisted shift in M_s.",
        "   - If the local point is above M_s^σ but ε_p > 0, apply Olson-Cohen with",
        "     calibrated (α, β) to compute strain-induced f_α′.",
        "3. Sum the volume of newly-transformed α′ in the plastic zone.",
        "4. Compute the volume-expansion-induced compressive residual stress field around",
        "   the crack tip → **ΔK_IC** (toughening contribution).",
        "5. Validate against Mondière's M54 commercial K_IC = 110 MPa·m^(1/2).",
        "",
        "All the pieces are in place; the synthesis is Phase 3.5 work.",
    ),
]


def main() -> None:
    nb = nbf.v4.new_notebook()
    nb["cells"] = CELLS
    nb["metadata"] = {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    }
    out = Path("notebooks/02_trip_toughening.ipynb")
    out.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, out)
    print(f"wrote {out} with {len(CELLS)} cells")


if __name__ == "__main__":
    main()
